### ISSUE TITLE
Proxy does not work for PUT/POST requests

### ISSUE THREAD

**Issue by santoshaherkar** [networknt/light-proxy#34]
I am getting "UT005028: Proxy request to {endpoint} failed" error when I try to call PUT/POST endpoints on the backend service.  GET calls worked fine though.
Note: we are using light-proxy v1.6.4

**Comment by stevehu** [comment]
@santoshaherkar Thanks a lot for raising this issue. For performance reason, we need to disable the body handler and skip the body validation on the light-proxy as we have discussed. As you have suggested, I have updated the document site to add a new section for the special configuration. Please review the document and let me know if anything is missing.  Thanks. 

https://doc.networknt.com/service/proxy/body-validation/
