### ISSUE TITLE
use the shared handlers from light-4j ingress-proxy module 

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-proxy#70]
light-4j ingress-proxy defined proxy handlers and it can be use for light-proxy project

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [use the shared handlers from light-4j ingress-proxy module light-proxy master](https://trello.com/c/KerdXyRu/1104-use-the-shared-handlers-from-light-4j-ingress-proxy-module-light-proxy-master)
